ktor:
    application:
        modules:
            - ApplicationKt.module
    deployment:
        host: "0.0.0.0"
        sslPort: 8443
    security:
        ssl:
            keyStore: "keystore.jks"
            keyAlias: "myKeyAlias"
            keyStorePassword: "qwerty"
            privateKeyPassword: "qwerty"